import { Sidebar } from '@/components/layout/Sidebar';
import { Topbar } from '@/components/layout/Topbar';
import { adminNavigation } from '@/lib/navigation';

export default function AdminDashboard() {
  const stats = [['Total applications','12,450'],['Pending verification','2,840'],['Deficiencies','624'],['Under selection','1,420']];
  return <div><Topbar role="MoTA Administration" /><Sidebar items={adminNavigation} title="Administration" /><main className="min-w-0 p-5 lg:ml-64 lg:p-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-medium text-[#2563A8]">Administration</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Overview</h1><p className="mt-1 text-sm text-slate-500">Monitor applications, verification and workflow progress.</p>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([a,b])=><div key={a} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{a}</p><p className="mt-2 text-2xl font-bold text-slate-950">{b}</p></div>)}</div>
    <div className="mt-7 grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Application pipeline</h2><div className="mt-5 space-y-4">{[['Submitted','12,450'],['Verification','4,230'],['Scrutiny','2,840'],['Screening','1,420'],['Selection','840']].map(([a,b])=><div key={a}><div className="flex justify-between text-sm"><span className="text-slate-600">{a}</span><span className="font-semibold text-slate-900">{b}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-[#2563A8]" style={{width:`${Math.max(8, Number(b.replace(',',''))/12450*100)}%`}} /></div></div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Priority review queue</h2><div className="mt-4 space-y-3">{[['NFST-2026-00125','Document mismatch'],['NOS-2026-00421','Missing document'],['NFST-2026-00781','OCR uncertainty']].map(([id,issue])=><div key={id} className="rounded-lg border border-slate-100 p-4"><p className="text-sm font-semibold text-slate-900">{id}</p><p className="mt-1 text-xs text-slate-500">{issue}</p><button className="mt-3 text-xs font-semibold text-[#173F7A]">Review application →</button></div>)}</div></section></div>
  </div></main></div>;
}
